# Generated by Django 3.2.25 on 2024-11-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelss',
            name='phone',
            field=models.CharField(default=3, max_length=12),
            preserve_default=False,
        ),
    ]
